# Generated by Django 3.2.4 on 2021-12-21 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=120)),
                ('password', models.CharField(max_length=150)),
                ('contact_no', models.CharField(max_length=15)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=10)),
                ('date_of_birth', models.DateField()),
                ('blood_group', models.CharField(max_length=10)),
                ('avatar', models.ImageField(upload_to='avatar/')),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
