# Generated by Django 3.2.4 on 2021-12-22 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testing_time', models.DateTimeField()),
                ('report_type', models.CharField(max_length=20)),
                ('pressure', models.CharField(max_length=10)),
                ('height', models.FloatField()),
                ('weight', models.CharField(max_length=10)),
                ('report_time', models.DateTimeField()),
                ('test_description', models.CharField(max_length=300)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tracker.appointment')),
            ],
        ),
    ]
