# Generated by Django 3.2.4 on 2021-12-23 03:06

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_alter_prescription_appointment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('on_holiday', models.BooleanField(default=False)),
                ('available_days', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('doctor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tracker.doctor')),
            ],
        ),
    ]
